### ISSUE TITLE
Use two datePicker and select period date

### ISSUE THREAD

**Issue by enaeim** [majidh1/Mh1PersianDatePicker#2]
Hi majid.

Thanks for your simple, pretty and practical datepicker.

I want to use two datepicker for select period of date (e.g. from 1399/02/20 to 1399/02/25). Thus, when the "start date" is selected, the "end date" should not be less than the start date and vice versa. Please tell me, how can I do this with your datepicker?

Thanks for your guidance.

**Comment by majidh1** [comment]
Hi,This date picker has not this ability, but you can check the validation of your input date on onchange.
Watch this link, i think this is almost what you want
https://www.iafi.ir/Home/FundReturnCalculator
