### ISSUE TITLE
مشکل با نشان دادن تاریخ امروز

### ISSUE THREAD

**Issue by ghost** [majidh1/Mh1PersianDatePicker#3]
سلام
وقت به خیر
یک سوال داشتم، بنده وقتی دکمه امروز را کلیک می‌کنم تاریخ امروز را نشان نمی‌دهد
برای تصحیح این فرایند راهنمایی می‌کنید؟

**Comment by majidh1** [comment]
تاریخ امروز باید به datepicker داده شود. پارامتر دوم متد show برابر با مقدار today است
Mh1PersianDatePicker.Show(this, '1399/11/29');
پیشنهاد میکنم نسخه جدید رو استفاده کنید که today رو به صورت خودکار انجام می‌دهد
https://github.com/majidh1/jalaliDatePicker
